name: Deploy Docs

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r doccer_requirements.txt
      - run: |
          python main.py main.py docs mkdocs.yml
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings
      - run: pip install pytkdocs[numpy-style]
      - run: mkdocs gh-deploy --force
